apiVersion: v1
kind: Secret
metadata:
  name: devops-secrets
type: Opaque
stringData:
  api-key: "2f5ae96c-b558-4c7b-a590-a501ae1c3f6c"
  jwt-secret: "change-this-to-a-strong-secret-in-production"
  jwt-issuer: "devops-microservice"