apiVersion: v1
kind: Service
metadata:
  name: devops-microservice
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  selector:
    app: devops-microservice
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  type: LoadBalancer  # LOAD BALANCER SEGÃšN PDF
  sessionAffinity: None
  externalTrafficPolicy: Cluster